services:

    payment.bridge:
        class: PaymentSuite\PaymentBridgeBundle\Services\PaymentBridge
        arguments:
            entity.manager: "@doctrine.orm.entity_manager"

    payment.event.listener:
        class: PaymentSuite\PaymentBridgeBundle\EventListener\Payment
        arguments:
            entity.manager: "@doctrine.orm.entity_manager"
            mailer: @mailer
        tags:
            - { name: kernel.event_listener, event: payment.order.success, method: onPaymentSuccess }
            - { name: kernel.event_listener, event: payment.order.fail, method: onPaymentFail }